-- Crie um dataframe contendo os 10 principais produtos químicos prescritos por região
SELECT
   REGIONAL_OFFICE_NAME
  ,BNF_DESCRIPTION
  ,SUM(TOTAL_QUANTITY)   AS QTD_PRESCRITA
FROM `bronze.TB_ANALITICO_PRESCRIPTIONS`
GROUP BY 
   REGIONAL_OFFICE_NAME
  ,BNF_DESCRIPTION
ORDER BY QTD_PRESCRITA DESC LIMIT 10;

-- Quais produtos químicos prescritos tiveram a maior somatória de custos por mês? Liste os 10 primeiros
SELECT
   BNF_DESCRIPTION
  ,SUM(ACTUAL_COST)   AS TOTAL_CUSTOS
FROM `bronze.TB_ANALITICO_PRESCRIPTIONS`
GROUP BY 
   BNF_DESCRIPTION
ORDER BY TOTAL_CUSTOS DESC LIMIT 10;

-- Quais são as precrições mais comuns? 
SELECT
   BNF_DESCRIPTION
  ,SUM(TOTAL_QUANTITY)   AS QTD_PRESCRITA
FROM `bronze.TB_ANALITICO_PRESCRIPTIONS`
GROUP BY 
   BNF_DESCRIPTION
ORDER BY QTD_PRESCRITA DESC LIMIT 10;

-- Qual produto químico é mais prescrito por cada prescriber?
WITH DS_PRODUTO_PRESCRIBER AS (
  SELECT 
    PRACTICE_NAME
    ,BNF_DESCRIPTION
    ,SUM(TOTAL_QUANTITY)   AS QTD_PRESCRITA
  FROM `bronze.TB_ANALITICO_PRESCRIPTIONS`
  GROUP BY 
    PRACTICE_NAME
    ,BNF_DESCRIPTION
  ORDER BY QTD_PRESCRITA DESC
)
  SELECT 
     PRACTICE_NAME 
    ,BNF_DESCRIPTION
  FROM DS_PRODUTO_PRESCRIBER    AS DPP
  WHERE QTD_PRESCRITA = (SELECT MAX(QTD_PRESCRITA) FROM DS_PRODUTO_PRESCRIBER AS DP WHERE DP.PRACTICE_NAME = DPP.PRACTICE_NAME);

-- Quantos prescribers foram adicionados no ultimo mês? 
SELECT 
  COUNT(DISTINCT PRACTICE_NAME)             AS QTD_PRESCRIBER_ADICIONADO
FROM `bronze.TB_ANALITICO_PRESCRIPTIONS`    AS TAP
WHERE 
  YEAR_MONTH > CAST(FORMAT_DATE('%Y%m',DATE_SUB(DATE_SUB(CURRENT_DATE, INTERVAL (EXTRACT(DAY FROM CURRENT_DATE)-1) day), INTERVAL 1 MONTH)) AS INT64) 
  AND PRACTICE_NAME NOT IN (
                    SELECT 
                      PRACTICE_NAME 
                    FROM `bronze.TB_ANALITICO_PRESCRIPTIONS` AS TA 
                    WHERE 
                      YEAR_MONTH <= CAST(FORMAT_DATE('%Y%m',DATE_SUB(DATE_SUB(CURRENT_DATE, INTERVAL (EXTRACT(DAY FROM CURRENT_DATE)-1) day), INTERVAL 1 MONTH)) AS INT64)
  );

-- Quais prescribers atuam em mais de uma região? Ordene por quantidade de regiões antendidas
SELECT 
  PRACTICE_NAME 
  ,COUNT(DISTINCT REGIONAL_OFFICE_NAME)   AS QTD_REGIAO_ATENDIDA
FROM 
  `bronze.TB_ANALITICO_PRESCRIPTIONS`
GROUP BY
  PRACTICE_NAME
HAVING
  QTD_REGIAO_ATENDIDA > 1
ORDER BY QTD_REGIAO_ATENDIDA DESC;

-- Qual o preço médio dos químicos prescritos no ultimo mês coletado?
SELECT 
   BNF_DESCRIPTION
  ,AVG(ACTUAL_COST)     AS PRECO_MEDIO
FROM   
  `bronze.TB_ANALITICO_PRESCRIPTIONS`
WHERE 
    YEAR_MONTH BETWEEN CAST(FORMAT_DATE('%Y%m',DATE_SUB(DATE_SUB(CURRENT_DATE, INTERVAL (EXTRACT(DAY FROM CURRENT_DATE)-1) day), INTERVAL 1 MONTH)) AS INT64) AND CAST(FORMAT_DATE('%Y%m',DATE_SUB(DATE_SUB(CURRENT_DATE, INTERVAL (EXTRACT(DAY FROM CURRENT_DATE)-1) day), INTERVAL 2 MONTH)) AS INT64)
GROUP BY 
  BNF_DESCRIPTION;

-- Gere uma tabela que contenha apenas a prescrição de maior valor de cada usuário
WITH DS_PRODUTO_PRESCRIBER AS (
  SELECT 
    PRACTICE_NAME
    ,BNF_DESCRIPTION
    ,MAX(ACTUAL_COST)   AS VALOR
  FROM `bronze.TB_ANALITICO_PRESCRIPTIONS`
  GROUP BY 
    PRACTICE_NAME
    ,BNF_DESCRIPTION
)
  SELECT 
     PRACTICE_NAME 
    ,BNF_DESCRIPTION
  FROM DS_PRODUTO_PRESCRIBER    AS DPP
  WHERE VALOR = (SELECT MAX(VALOR) FROM DS_PRODUTO_PRESCRIBER AS DP WHERE DP.PRACTICE_NAME = DPP.PRACTICE_NAME);

